baseurl: "https://pensive-curie-035758.netlify.app/"
title: Noisy Affiliated Utility
author: Edmund Baker
canonifyurls: yes
languagecode: en
theme: hugo-black-and-light-theme
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
pygmentsstyle: bw
pygmentscodefences: yes
params:
  disableWebFonts: no
  sitename: Noisy Affiliated Utility
menu:
  main:
    - name: Ed Mainpage
      url: https://github.com/davidhampgonsalves/hugo-black-and-light-theme
    - name: NAU Model
      url: https://github.com/davidhampgonsalves/hugo-black-and-light-theme
    

markup:
  goldmark:
    renderer:
      unsafe: true

